// V15 golden replays (verification plan V15): each fixture's commands, replayed from its recorded start, reproduce the
// recorded events and the stateHash after every step, byte-exactly. The fixtures are generated by tooling/v15-golden.ts
// (`pnpm golden:v15`); this test only reads them.
import { describe, expect, it } from 'vitest';
import game3Json from './__fixtures__/golden/v15-game-3p.json';
import game4Json from './__fixtures__/golden/v15-game-4p.json';
import shortageJson from './__fixtures__/golden/v15e-bank-shortage.json';
import setup3Json from './__fixtures__/golden/v15-setup-3p.json';
import setup4Json from './__fixtures__/golden/v15-setup-4p.json';
import type { ActionType, Command, GameEvent, GameInit, ReduceResult } from './index';
import { createGame, reduce, replay, replayFrom, stateHash } from './index';
import { RESOURCES, type GameState, type Phase, type ResourceCounts } from './state';
import { buildState, validateInvariants, type StateSpec } from './testing';

interface Step {
  readonly command: Command;
  readonly events: readonly GameEvent[];
  readonly stateHash: string;
}

interface SetupFixture {
  readonly init: GameInit;
  readonly board: {
    readonly hexes: readonly (readonly [string, string, number | null])[];
    readonly harbors: readonly (readonly [string, string])[];
    readonly robber: string;
  };
  readonly initialStateHash: string;
  readonly steps: readonly Step[];
  readonly final: {
    readonly phase: Phase;
    readonly turn: unknown;
    readonly hands: readonly ResourceCounts[];
    readonly bank: ResourceCounts;
  };
}

interface GameFixture {
  readonly init: GameInit;
  readonly initialStateHash: string;
  readonly steps: readonly Step[];
  readonly final: {
    readonly phase: Phase;
    readonly turn: unknown;
    readonly hands: readonly ResourceCounts[];
    readonly bank: ResourceCounts;
    readonly awards: GameState['awards'];
  };
}

interface ReplayFixture {
  readonly buildStateSpec: StateSpec;
  readonly initialStateHash: string;
  readonly steps: readonly Step[];
}

/** Every command was accepted with the recorded events, and hashes[i] is the recorded hash after step i. */
function expectSteps(results: readonly ReduceResult[], hashes: readonly string[], steps: readonly Step[]): void {
  expect(results).toHaveLength(steps.length);
  results.forEach((r, i) => {
    expect(r.ok, `step ${i}`).toBe(true);
    if (r.ok) expect(r.events, `events of step ${i}`).toEqual(steps[i]!.events);
  });
  expect(hashes).toEqual(steps.map((s) => s.stateHash));
}

describe.each([
  ['4 players', setup4Json as unknown as SetupFixture],
  ['3 players', setup3Json as unknown as SetupFixture],
])('V15 setup golden, %s', (_label, fixture) => {
  const commands = fixture.steps.map((s) => s.command);

  it('createGame gives the recorded board and initial stateHash', () => {
    const created = createGame(fixture.init);
    expect(created.ok).toBe(true);
    if (!created.ok) return;
    const { board, robber } = created.state;
    expect(board.hexes.map((h) => [h.id, h.terrain, h.token])).toEqual(fixture.board.hexes);
    expect(board.harbors.map((h) => [h.edge, h.kind])).toEqual(fixture.board.harbors);
    expect(robber).toBe(fixture.board.robber);
    expect(stateHash(created.state)).toBe(fixture.initialStateHash);
  });

  it('replay(init, commands) reproduces every event and stateHash, and equals replayFrom(createGame(init).state)', () => {
    const replayed = replay(fixture.init, commands);
    expectSteps(replayed.results, replayed.hashes, fixture.steps);
    const created = createGame(fixture.init);
    if (!created.ok) throw new Error('createGame rejected the fixture init');
    expect(replayFrom(created.state, commands)).toEqual(replayed);
  });

  it('the draft follows the snake order and ends in preRoll of turn 1 with the recorded hands and bank', () => {
    const n = fixture.init.playerCount;
    const order = [...Array(n).keys(), ...[...Array(n).keys()].reverse()];
    expect(commands.map((c) => c.by)).toEqual(order.flatMap((seat) => [seat, seat]));
    const end = replay(fixture.init, commands).state;
    expect(end.phase).toEqual(fixture.final.phase);
    expect(end.turn).toEqual(fixture.final.turn);
    expect(end.players.map((p) => p.hand)).toEqual(fixture.final.hands);
    expect(end.bank).toEqual(fixture.final.bank);
  });
});

describe('V15(e) bank-shortage golden', () => {
  const fixture = shortageJson as unknown as ReplayFixture;

  it('replayFrom(buildState(spec), commands) reproduces every event and stateHash', () => {
    const start = buildState(fixture.buildStateSpec);
    expect(stateHash(start)).toBe(fixture.initialStateHash);
    const replayed = replayFrom(start, fixture.steps.map((s) => s.command));
    expectSteps(replayed.results, replayed.hashes, fixture.steps);
  });

  it('covers both shortage outcomes: some short resource pays exactly one seat, some pays nobody', () => {
    const rolls = fixture.steps.flatMap((s) => s.events).filter((e) => e.kind === 'diceRolled');
    const outcomes = rolls.flatMap((e) =>
      e.shortage.map((r) => e.gains.filter((g) => g[r] > 0).length),
    );
    expect(outcomes).toContain(1);
    expect(outcomes).toContain(0);
  });
});

const ACTION_TYPES: readonly ActionType[] = [
  'placeSettlement', 'placeRoad', 'buildCity', 'rollDice', 'discard', 'moveRobber', 'buyDevCard', 'playKnight',
  'playRoadBuilding', 'playYearOfPlenty', 'playMonopoly', 'maritimeTrade', 'proposeTrade', 'respondTrade', 'confirmTrade',
  'cancelTrade', 'endTurn',
];

describe.each([
  ['4 players', game4Json as unknown as GameFixture],
  ['3 players', game3Json as unknown as GameFixture],
])('V15 full-game golden, %s', (_label, fixture) => {
  const commands = fixture.steps.map((s) => s.command);

  it('replay(init, commands) reproduces every event and stateHash, and equals replayFrom(createGame(init).state)', () => {
    const created = createGame(fixture.init);
    if (!created.ok) throw new Error('createGame rejected the fixture init');
    expect(stateHash(created.state)).toBe(fixture.initialStateHash);
    const replayed = replay(fixture.init, commands);
    expectSteps(replayed.results, replayed.hashes, fixture.steps);
    expect(replayFrom(created.state, commands)).toEqual(replayed);
  });

  it('ends in gameOver for the active seat with the recorded hands, bank and awards; every state passes the invariants', () => {
    const created = createGame(fixture.init);
    if (!created.ok) throw new Error('createGame rejected the fixture init');
    let state = created.state;
    for (const command of commands) {
      const r = reduce(state, command);
      if (!r.ok) throw new Error(r.reason);
      state = r.state;
      expect(validateInvariants(state)).toEqual([]);
    }
    expect(state.phase).toEqual(fixture.final.phase);
    expect(state.phase).toEqual({ name: 'gameOver', winner: state.turn.active });
    expect(state.turn).toEqual(fixture.final.turn);
    expect(state.players.map((p) => p.hand)).toEqual(fixture.final.hands);
    expect(state.bank).toEqual(fixture.final.bank);
    expect(state.awards).toEqual(fixture.final.awards);
  });

  it('covers every Action type, both awards, the dice/steal/devDeck streams and a reversed Year of Plenty take (D20)', () => {
    expect(new Set(commands.map((c) => c.action.type))).toEqual(new Set(ACTION_TYPES));
    const events = fixture.steps.flatMap((s) => s.events);
    expect(fixture.final.awards.longestRoad).not.toBeNull();
    expect(fixture.final.awards.largestArmy).not.toBeNull();
    for (const kind of ['diceRolled', 'stoleDetail', 'devBoughtDetail', 'discarded', 'maritimeTraded', 'gameOver']) {
      expect(events.some((e) => e.kind === kind), kind).toBe(true);
    }
    // D20: the command keeps the order it was sent in; the event lists the take in RESOURCES order.
    const reversed = fixture.steps.find(
      (s) => s.command.action.type === 'playYearOfPlenty' && RESOURCES.indexOf(s.command.action.take[0]) > RESOURCES.indexOf(s.command.action.take[1]),
    );
    expect(reversed).toBeDefined();
    if (reversed?.command.action.type !== 'playYearOfPlenty') return;
    const [a, b] = reversed.command.action.take;
    expect(reversed.events).toContainEqual(expect.objectContaining({ kind: 'devPlayed', card: 'yearOfPlenty', picks: [b, a] }));
  });
});
