// V15 golden replays (verification plan V15): each fixture's commands, replayed from its recorded start, reproduce the
// recorded events and the stateHash after every step, byte-exactly. The fixtures are generated by tooling/v15-golden.ts
// (`pnpm golden:v15`); this test only reads them.
import { describe, expect, it } from 'vitest';
import shortageJson from './__fixtures__/golden/v15e-bank-shortage.json';
import setup3Json from './__fixtures__/golden/v15-setup-3p.json';
import setup4Json from './__fixtures__/golden/v15-setup-4p.json';
import type { Command, GameEvent, GameInit, ReduceResult } from './index';
import { createGame, replay, replayFrom, stateHash } from './index';
import type { Phase, ResourceCounts } from './state';
import { buildState, type StateSpec } from './testing';

interface Step {
  readonly command: Command;
  readonly events: readonly GameEvent[];
  readonly stateHash: string;
}

interface SetupFixture {
  readonly init: GameInit;
  readonly board: {
    readonly hexes: readonly (readonly [string, string, number | null])[];
    readonly harbors: readonly (readonly [string, string])[];
    readonly robber: string;
  };
  readonly initialStateHash: string;
  readonly steps: readonly Step[];
  readonly final: {
    readonly phase: Phase;
    readonly turn: unknown;
    readonly hands: readonly ResourceCounts[];
    readonly bank: ResourceCounts;
  };
}

interface ReplayFixture {
  readonly buildStateSpec: StateSpec;
  readonly initialStateHash: string;
  readonly steps: readonly Step[];
}

/** Every command was accepted with the recorded events, and hashes[i] is the recorded hash after step i. */
function expectSteps(results: readonly ReduceResult[], hashes: readonly string[], steps: readonly Step[]): void {
  expect(results).toHaveLength(steps.length);
  results.forEach((r, i) => {
    expect(r.ok, `step ${i}`).toBe(true);
    if (r.ok) expect(r.events, `events of step ${i}`).toEqual(steps[i]!.events);
  });
  expect(hashes).toEqual(steps.map((s) => s.stateHash));
}

describe.each([
  ['4 players', setup4Json as unknown as SetupFixture],
  ['3 players', setup3Json as unknown as SetupFixture],
])('V15 setup golden, %s', (_label, fixture) => {
  const commands = fixture.steps.map((s) => s.command);

  it('createGame gives the recorded board and initial stateHash', () => {
    const created = createGame(fixture.init);
    expect(created.ok).toBe(true);
    if (!created.ok) return;
    const { board, robber } = created.state;
    expect(board.hexes.map((h) => [h.id, h.terrain, h.token])).toEqual(fixture.board.hexes);
    expect(board.harbors.map((h) => [h.edge, h.kind])).toEqual(fixture.board.harbors);
    expect(robber).toBe(fixture.board.robber);
    expect(stateHash(created.state)).toBe(fixture.initialStateHash);
  });

  it('replay(init, commands) reproduces every event and stateHash, and equals replayFrom(createGame(init).state)', () => {
    const replayed = replay(fixture.init, commands);
    expectSteps(replayed.results, replayed.hashes, fixture.steps);
    const created = createGame(fixture.init);
    if (!created.ok) throw new Error('createGame rejected the fixture init');
    expect(replayFrom(created.state, commands)).toEqual(replayed);
  });

  it('the draft follows the snake order and ends in preRoll of turn 1 with the recorded hands and bank', () => {
    const n = fixture.init.playerCount;
    const order = [...Array(n).keys(), ...[...Array(n).keys()].reverse()];
    expect(commands.map((c) => c.by)).toEqual(order.flatMap((seat) => [seat, seat]));
    const end = replay(fixture.init, commands).state;
    expect(end.phase).toEqual(fixture.final.phase);
    expect(end.turn).toEqual(fixture.final.turn);
    expect(end.players.map((p) => p.hand)).toEqual(fixture.final.hands);
    expect(end.bank).toEqual(fixture.final.bank);
  });
});

describe('V15(e) bank-shortage golden', () => {
  const fixture = shortageJson as unknown as ReplayFixture;

  it('replayFrom(buildState(spec), commands) reproduces every event and stateHash', () => {
    const start = buildState(fixture.buildStateSpec);
    expect(stateHash(start)).toBe(fixture.initialStateHash);
    const replayed = replayFrom(start, fixture.steps.map((s) => s.command));
    expectSteps(replayed.results, replayed.hashes, fixture.steps);
  });

  it('covers both shortage outcomes: some short resource pays exactly one seat, some pays nobody', () => {
    const rolls = fixture.steps.flatMap((s) => s.events).filter((e) => e.kind === 'diceRolled');
    const outcomes = rolls.flatMap((e) =>
      e.shortage.map((r) => e.gains.filter((g) => g[r] > 0).length),
    );
    expect(outcomes).toContain(1);
    expect(outcomes).toContain(0);
  });
});
