// Generates E-INT's golden replay fixtures (task E-INT; verification plan V15 (c), (d), (f), (g)) into
// packages/engine/src/__fixtures__/golden/eint-*.json. They are Build-owned; V-a's v15-*.json are generated by
// tooling/v15-golden.ts. tooling/golden-runner.test.ts replays every fixture in that directory and asserts every step.
//
// Each file is {description, cases: [{name, buildStateSpec, initialStateHash, steps}]}. An accepted step records
// {command, events, stateHash}; a rejection step records {command, rejected: <reason>, events: [], stateHash} with the
// stateHash unchanged. Generation aborts if any step's outcome differs from the script.
//
// Run with `pnpm golden:eint`. Regenerate only together with a rule or serialization change that is meant to move the
// hashes, and say so in that PR.
import { writeFileSync } from 'node:fs';
import {
  legalActions,
  reduce,
  stateHash,
  type Action,
  type Command,
  type EdgeId,
  type EngineReasonCode,
  type GameEvent,
  type GameState,
  type HexId,
  type Seat,
  type VertexId,
} from '../packages/engine/src/index';
import { buildState, type StateSpec } from '../packages/engine/src/testing/index';
import { STANDARD_TOPOLOGY as T } from '../packages/engine/src/topology';

const OUT = new URL('../packages/engine/src/__fixtures__/golden/', import.meta.url);

interface Step {
  readonly command: Command;
  readonly rejected?: EngineReasonCode;
  readonly events: readonly GameEvent[];
  readonly stateHash: string;
}

/** One scripted step: a command, plus the rejection reason when it must be rejected. */
type Planned = readonly [Command, EngineReasonCode?];

/** Plays `script` from buildState(spec) and records every step; throws when an outcome differs from the script. */
function recordCase(name: string, spec: StateSpec, script: (s: GameState, i: number) => Planned | null) {
  const start = buildState(spec);
  let s = start;
  const steps: Step[] = [];
  for (let i = 0; ; i++) {
    const planned = script(s, i);
    if (planned === null) break;
    const [command, rejected] = planned;
    const r = reduce(s, command);
    if (rejected !== undefined) {
      if (r.ok || r.reason !== rejected) throw new Error(`${name} step ${i}: expected ${rejected}, got ${r.ok ? 'ok' : r.reason}`);
      steps.push({ command, rejected, events: [], stateHash: stateHash(s) });
      continue;
    }
    if (!r.ok) throw new Error(`${name} step ${i}: ${JSON.stringify(command)} rejected with ${r.reason}`);
    s = r.state;
    steps.push({ command, events: r.events, stateHash: stateHash(s) });
  }
  return { name, buildStateSpec: spec, initialStateHash: stateHash(start), steps, end: s };
}

const cmd = (by: Seat, action: Action): Command => ({ by, action });
const seq = (...planned: Planned[]) => (_s: GameState, i: number): Planned | null => planned[i] ?? null;
const ZERO = { brick: 0, lumber: 0, wool: 0, grain: 0, ore: 0 };

function edgeBetween(a: VertexId, b: VertexId): EdgeId {
  const e = T.vertexEdges(a).find((x) => T.edgeVertices(x).includes(b));
  if (!e) throw new Error(`no edge ${a}–${b}`);
  return e;
}
const path = (vs: readonly VertexId[]): EdgeId[] => vs.slice(1).map((v, i) => edgeBetween(vs[i]!, v));
/** The top zigzag (NW, N, NE corners) along a row of hexes. */
function topZigzag(...hs: HexId[]): VertexId[] {
  const vs: VertexId[] = [];
  for (const h of hs) {
    const [n, ne, , , , nw] = T.hexCorners(h);
    if (vs.at(-1) !== nw) vs.push(nw!);
    vs.push(n!, ne!);
  }
  return vs;
}
/** `count` vertices pairwise ≥ 2 apart and not adjacent to anything in `avoid`. */
function spread(count: number, avoid: ReadonlySet<VertexId> = new Set()): VertexId[] {
  const taken: VertexId[] = [];
  const blocked = (v: VertexId) => avoid.has(v) || taken.includes(v) || T.vertexNeighbours(v).some((n) => taken.includes(n) || avoid.has(n));
  for (const v of T.vertices) {
    if (taken.length === count) break;
    if (!blocked(v)) taken.push(v);
  }
  return taken;
}

/** Steps for seats other than `seat` to roll and end their turns, until `seat` is active again in preRoll. */
function passRound(s: GameState, seat: Seat): Planned | null {
  if (s.turn.active === seat) return null;
  return [cmd(s.turn.active, s.phase.name === 'preRoll' ? { type: 'rollDice' } : { type: 'endTurn' })];
}

// ── (c) each development card ─────────────────────────────────────────────────────────────────────────────────────

function devCardsFixture() {
  const home: VertexId = 'v:0,0,N';
  const homeRoad = T.vertexEdges(home)[0]!;
  const [o1, o2, o3] = spread(3, new Set([home, ...T.edgeVertices(homeRoad)]));
  const spec = {
    pieces: [
      { seat: 0, settlements: [home], roads: [homeRoad] },
      { seat: 1, settlements: [o1!] },
      { seat: 2, settlements: [o2!] },
      { seat: 3, settlements: [o3!] },
    ],
    hands: { 0: { wool: 1, grain: 1, ore: 1 }, 1: { ore: 2, brick: 1 }, 2: { ore: 1 }, 3: { wool: 2 } },
    devCards: {
      0: [
        { kind: 'knight', boughtOnTurn: 0 },
        { kind: 'roadBuilding', boughtOnTurn: 0 },
        { kind: 'yearOfPlenty', boughtOnTurn: 0 },
        { kind: 'monopoly', boughtOnTurn: 0 },
        { kind: 'victoryPoint', boughtOnTurn: 0 },
      ],
    },
    turn: { number: 3 },
    phase: { name: 'preRoll' },
    // Never a 7: every roll is 2 + 3.
    rng: { dice: { scripted: Array<number>(64).fill(0).map((_, i) => (i % 2 === 0 ? 2 : 3)), seed: 'eint-c' } },
  } satisfies StateSpec;
  // Seat 0 plays one card per turn: Knight (pre-roll), Road Building, Year of Plenty (take sent reversed, D20),
  // Monopoly, and buys a card on the first turn; the VP card stays hidden in hand throughout.
  let phaseOfTurn = 0;
  const script = (s: GameState): Planned | null => {
    if (s.turn.active !== 0) return passRound(s, 0);
    const legal = legalActions(s, 0);
    switch (phaseOfTurn) {
      case 0: // turn 1: Knight before rolling, rob seat 1, roll, buy a card, end
        if (s.phase.name === 'preRoll' && legal.playKnight) return [cmd(0, { type: 'playKnight' })];
        if (s.phase.name === 'moveRobber') {
          const t = legal.moveRobber.find((m) => m.victims.includes(1))!;
          return [cmd(0, { type: 'moveRobber', hex: t.hex, victim: 1 })];
        }
        if (s.phase.name === 'preRoll') return [cmd(0, { type: 'rollDice' })];
        if (legal.buyDevCard) return [cmd(0, { type: 'buyDevCard' })];
        phaseOfTurn = 1;
        return [cmd(0, { type: 'endTurn' })];
      case 1: // turn 2: Road Building, two free roads
        if (s.phase.name === 'preRoll') return [cmd(0, { type: 'rollDice' })];
        if (s.phase.name === 'roadBuilding') return [cmd(0, { type: 'placeRoad', edge: legal.placeRoad[0]! })];
        if (legal.playRoadBuilding) return [cmd(0, { type: 'playRoadBuilding' })];
        phaseOfTurn = 2;
        return [cmd(0, { type: 'endTurn' })];
      case 2: // turn 3: Year of Plenty with the take sent in reverse canonical order
        if (s.phase.name === 'preRoll') return [cmd(0, { type: 'rollDice' })];
        if (legal.playYearOfPlenty.length > 0) return [cmd(0, { type: 'playYearOfPlenty', take: ['ore', 'brick'] })];
        phaseOfTurn = 3;
        return [cmd(0, { type: 'endTurn' })];
      case 3: // turn 4: Monopoly on ore
        if (s.phase.name === 'preRoll') return [cmd(0, { type: 'rollDice' })];
        if (legal.playMonopoly) return [cmd(0, { type: 'playMonopoly', resource: 'ore' })];
        phaseOfTurn = 4;
        return [cmd(0, { type: 'endTurn' })];
      default:
        return null;
    }
  };
  const c = recordCase('one of each development card over four turns', spec, script);
  const kinds = c.steps.map((st) => st.command.action.type);
  for (const k of ['playKnight', 'playRoadBuilding', 'playYearOfPlenty', 'playMonopoly', 'buyDevCard'] as const) {
    if (!kinds.includes(k)) throw new Error(`(c) misses ${k}`);
  }
  return { description: 'V15 (c): each development card — Knight, Road Building, Year of Plenty (reversed take), Monopoly, a purchase, and a held VP card.', cases: [c] };
}

// ── (d) Longest Road and Largest Army transfers, a broken road, a turn-start win ─────────────────────────────────────

function awardsFixture() {
  // Longest Road: seat 2 holds it with 6 roads; seat 0 places a settlement that cuts it, the award moves to seat 1,
  // which reaches the target (5) off-turn and wins at its own turn start (D3).
  const run2 = topZigzag('h:-2,0', 'h:-1,0', 'h:0,0');
  const run1 = topZigzag('h:-1,-1', 'h:0,-1', 'h:1,-1');
  const cut = run2[3]!;
  const spur = T.vertexNeighbours(cut).find((n) => !run2.includes(n))!;
  const seat1Settlements = spread(3, new Set([...run2, spur, ...run1]));
  const roadSpec = {
    rules: { vpTarget: 5 },
    pieces: [
      { seat: 0, roads: [edgeBetween(cut, spur)] },
      { seat: 1, settlements: seat1Settlements, roads: path(run1.slice(0, 6)) },
      { seat: 2, roads: path(run2) },
    ],
    hands: { 0: { brick: 1, lumber: 1, wool: 1, grain: 1 } },
    turn: { number: 5, active: 0 },
  } satisfies StateSpec;
  const road = recordCase('Longest Road broken by a settlement; the award moves to seat 1, which wins at its turn start (D3)', roadSpec, seq(
    [cmd(0, { type: 'placeSettlement', vertex: cut })],
    [cmd(0, { type: 'endTurn' })],
    [cmd(1, { type: 'rollDice' }), 'game_over'],
  ));
  if (road.end.phase.name !== 'gameOver' || road.end.phase.winner !== 1) throw new Error('(d) road: seat 1 must win at turn start');

  // Largest Army: seat 1 holds it with 3 knights; seat 0 (3 played) plays a 4th and takes it.
  const [h0, h1] = spread(2);
  const armySpec = {
    pieces: [
      { seat: 0, settlements: [h0!] },
      { seat: 1, settlements: [h1!] },
    ],
    playedDev: { 0: { knight: 3 }, 1: { knight: 3 } },
    awards: { largestArmy: 1 },
    devCards: { 0: [{ kind: 'knight', boughtOnTurn: 0 }] },
    turn: { number: 6, active: 0 },
  } satisfies StateSpec;
  const army = recordCase('Largest Army moves from seat 1 (3 knights) to seat 0 on its 4th knight', armySpec, (s, i) => {
    if (i === 0) return [cmd(0, { type: 'playKnight' })];
    if (s.phase.name === 'moveRobber') {
      const t = legalActions(s, 0).moveRobber[0]!;
      return [cmd(0, { type: 'moveRobber', hex: t.hex, victim: t.victims[0] ?? null })];
    }
    return null;
  });
  if (army.end.awards.largestArmy !== 0) throw new Error('(d) army: the award must move to seat 0');
  return { description: 'V15 (d): Longest Road and Largest Army transfers, including a broken road and a turn-start win (D3).', cases: [road, army] };
}

// ── (f) a 7 with three simultaneous discarders ───────────────────────────────────────────────────────────────────────

function sevenFixture() {
  const [v0, v1, v2, v3] = spread(4);
  const spec = {
    pieces: [
      { seat: 0, settlements: [v0!] },
      { seat: 1, settlements: [v1!] },
      { seat: 2, settlements: [v2!] },
      { seat: 3, settlements: [v3!] },
    ],
    // Seats 1–3 hold more than 7 cards (owe 4, 4, 5); seat 0, the roller, holds 7 and owes nothing.
    hands: {
      0: { brick: 3, ore: 4 },
      1: { brick: 2, lumber: 2, wool: 2, grain: 2 },
      2: { lumber: 4, ore: 5 },
      3: { wool: 5, grain: 5 },
    },
    phase: { name: 'preRoll' },
    turn: { number: 4 },
    rng: { dice: { scripted: [3, 4], seed: 'eint-f' } },
  } satisfies StateSpec;
  const c = recordCase('a 7: seats 1, 2 and 3 discard in any order, then the robber moves and steals', spec, (s, i) => {
    if (i === 0) return [cmd(0, { type: 'rollDice' })];
    if (s.phase.name === 'discard') {
      // Out of seat order on purpose: 3, then 1, then 2; seat 0 first tries (discard_not_required), then a discard
      // with the wrong count.
      const owed = s.phase.owed;
      if (i === 1) return [cmd(0, { type: 'discard', cards: { ...ZERO, brick: 1 } }), 'discard_not_required'];
      if (i === 2) return [cmd(3, { type: 'discard', cards: { ...ZERO, wool: 1 } }), 'wrong_discard_count'];
      if (i === 3) return [cmd(1, { type: 'endTurn' }), 'discard_pending'];
      const seat = ([3, 1, 2] as const).find((x) => (owed[x] ?? 0) > 0)!;
      const hand = s.players[seat]!.hand;
      let left = owed[seat]!;
      const cards = { ...ZERO };
      for (const r of ['brick', 'lumber', 'wool', 'grain', 'ore'] as const) {
        const take = Math.min(left, hand[r]);
        cards[r] = take;
        left -= take;
      }
      return [cmd(seat, { type: 'discard', cards })];
    }
    if (s.phase.name === 'moveRobber') {
      const t = legalActions(s, 0).moveRobber.find((m) => m.victims.length > 0)!;
      return [cmd(0, { type: 'moveRobber', hex: t.hex, victim: t.victims[0]! })];
    }
    if (s.phase.name === 'main' && i < 12) return [cmd(0, { type: 'endTurn' })];
    return null;
  });
  return { description: 'V15 (f): a 7 with three simultaneous discarders, discarding out of seat order, then robber + steal.', cases: [c] };
}

// ── (g) every engine rejection path, D18a order ──────────────────────────────────────────────────────────────────────

function rejectionsFixture() {
  const home: VertexId = 'v:0,0,N';
  const homeRoad = T.vertexEdges(home)[0]!;
  const base = {
    pieces: [{ seat: 0, settlements: [home], roads: [homeRoad] }, { seat: 1, settlements: [spread(1, new Set(T.vertexNeighbours(home).concat(home)))[0]!] }],
    turn: { number: 3 },
  } satisfies StateSpec;
  const far = T.vertices.find((v) => v !== home && !T.vertexNeighbours(home).includes(v) && T.vertexNeighbours(v).every((n) => !T.edgeVertices(homeRoad).includes(n)) && !T.edgeVertices(homeRoad).includes(v))!;
  const farEdge = T.vertexEdges(far).find((e) => T.edgeVertices(e).every((v) => v !== home && !T.edgeVertices(homeRoad).includes(v)))!;
  const cases: ReturnType<typeof recordCase>[] = [];
  const add = (name: string, spec: StateSpec, ...planned: Planned[]) => cases.push(recordCase(name, spec, seq(...planned)));

  // Turn codes and their precedence (D18a): malformed_action → game_over → discard_pending → not_your_turn → wrong_phase.
  add('malformed_action: an off-schema id, and a non-integer count (D14)', base,
    [cmd(0, { type: 'placeRoad', edge: 'e:not-an-edge' as EdgeId }), 'malformed_action'],
    [cmd(0, { type: 'maritimeTrade', give: 'brick', receive: 'ore', count: 1.5 }), 'malformed_action']);
  add('game_over beats every other check', { ...base, phase: { name: 'gameOver', winner: 0 } },
    [cmd(1, { type: 'rollDice' }), 'game_over'],
    [cmd(0, { type: 'endTurn' }), 'game_over']);
  const discardSpec = { ...base, hands: { 2: { ore: 8 } }, phase: { name: 'discard', owed: [0, 0, 4, 0], then: 'moveRobber' } } satisfies StateSpec;
  add('discard phase: discard_pending (any non-discard, any seat), discard_not_required, wrong_discard_count', discardSpec,
    [cmd(1, { type: 'endTurn' }), 'discard_pending'],
    [cmd(0, { type: 'endTurn' }), 'discard_pending'],
    [cmd(1, { type: 'discard', cards: { ...ZERO, ore: 1 } }), 'discard_not_required'],
    [cmd(2, { type: 'discard', cards: { ...ZERO, ore: 3 } }), 'wrong_discard_count'],
    [cmd(2, { type: 'discard', cards: { ...ZERO, brick: 4 } }), 'wrong_discard_count']);
  add('not_your_turn before wrong_phase (role first), and wrong_phase', base,
    [cmd(1, { type: 'rollDice' }), 'not_your_turn'],
    [cmd(1, { type: 'endTurn' }), 'not_your_turn'],
    [cmd(0, { type: 'respondTrade', tradeId: 1, accept: false }), 'not_your_turn'],
    [cmd(0, { type: 'rollDice' }), 'wrong_phase'],
    [cmd(2, { type: 'discard', cards: { ...ZERO, ore: 1 } }), 'wrong_phase'],
    [cmd(0, { type: 'moveRobber', hex: 'h:1,0', victim: null }), 'wrong_phase']);

  // Building: location → occupancy → distance → connectivity → pieces → resources.
  const [c1, c2, c3, c4] = spread(4, new Set([home, ...T.vertexNeighbours(home)]));
  add('building rejections', { ...base, hands: { 0: { brick: 1, lumber: 1, wool: 1, grain: 1 } } },
    [cmd(0, { type: 'buildCity', vertex: 'v:9,9,N' }), 'invalid_location'],
    [cmd(0, { type: 'buildCity', vertex: far }), 'invalid_location'],
    [cmd(0, { type: 'placeSettlement', vertex: home }), 'occupied'],
    [cmd(0, { type: 'placeSettlement', vertex: T.vertexNeighbours(home)[0]! }), 'distance_rule'],
    [cmd(0, { type: 'placeRoad', edge: farEdge }), 'not_connected'],
    [cmd(0, { type: 'buildCity', vertex: home }), 'insufficient_resources']);
  add('no_pieces_left: four cities already placed', {
    pieces: [{ seat: 0, settlements: [home], cities: [c1!, c2!, c3!, c4!] }],
    hands: { 0: { grain: 2, ore: 3 } },
    turn: { number: 3 },
  }, [cmd(0, { type: 'buildCity', vertex: home }), 'no_pieces_left']);

  // Robber.
  const robberSpec = { ...base, phase: { name: 'moveRobber', resume: 'main' } } satisfies StateSpec;
  const robber = buildState(robberSpec).robber;
  const empty = T.hexes.find((h) => h !== robber && T.hexCorners(h).every((v) => v !== home && !(base.pieces[1]!.settlements as readonly VertexId[]).includes(v)))!;
  add('robber rejections', robberSpec,
    [cmd(0, { type: 'moveRobber', hex: robber, victim: null }), 'robber_must_move'],
    [cmd(0, { type: 'moveRobber', hex: 'h:9,9', victim: null }), 'invalid_robber_hex'],
    [cmd(0, { type: 'moveRobber', hex: empty, victim: 1 }), 'invalid_steal_target']);

  // Development cards (D17: card rules before effects).
  const allCards = [
    ...Array<'knight'>(14).fill('knight'), ...Array<'victoryPoint'>(5).fill('victoryPoint'), 'roadBuilding', 'roadBuilding',
    'yearOfPlenty', 'yearOfPlenty', 'monopoly', 'monopoly',
  ] as const;
  add('dev_deck_empty: every card is held', {
    ...base,
    devDeck: [],
    devCards: { 2: allCards.map((kind) => ({ kind, boughtOnTurn: 0 })) },
    hands: { 0: { wool: 1, grain: 1, ore: 1 } },
  }, [cmd(0, { type: 'buyDevCard' }), 'dev_deck_empty']);
  add('dev card rules', {
    ...base,
    devCards: { 0: [{ kind: 'knight', boughtOnTurn: 3 }, { kind: 'yearOfPlenty', boughtOnTurn: 0 }, { kind: 'monopoly', boughtOnTurn: 0 }] },
    hands: { 1: { ore: 19 } },
  },
    [cmd(0, { type: 'playRoadBuilding' }), 'dev_card_not_owned'],
    [cmd(0, { type: 'playKnight' }), 'dev_card_bought_this_turn'],
    [cmd(0, { type: 'playYearOfPlenty', take: ['ore', 'ore'] }), 'bank_insufficient'],
    [cmd(0, { type: 'playYearOfPlenty', take: ['wool', 'brick'] })],
    [cmd(0, { type: 'playMonopoly', resource: 'ore' }), 'dev_card_already_played']);

  // Trades.
  const offer = { id: 4, from: 0, give: { ...ZERO, wool: 1 }, get: { ...ZERO, ore: 1 }, responses: ['self', 'accepted', 'pending', 'declined'] } as const;
  add('trade rejections', { ...base, hands: { 0: { wool: 1, brick: 4 }, 2: { ore: 19 } }, trade: offer },
    [cmd(0, { type: 'proposeTrade', give: ZERO, get: { ...ZERO, ore: 1 } }), 'invalid_trade'],
    [cmd(0, { type: 'maritimeTrade', give: 'brick', receive: 'brick', count: 1 }), 'invalid_trade'],
    [cmd(0, { type: 'maritimeTrade', give: 'brick', receive: 'ore', count: 1 }), 'bank_insufficient'],
    [cmd(0, { type: 'cancelTrade', tradeId: 3 }), 'trade_not_found'],
    [cmd(0, { type: 'confirmTrade', tradeId: 4, partner: 2 }), 'trade_not_accepted'],
    [cmd(0, { type: 'confirmTrade', tradeId: 4, partner: 1 }), 'trade_stale']);

  // System command: a skip of a seat the game is not waiting on (non-active, outside discard) → skip_not_allowed.
  add('skip_not_allowed (system skipSeat of a seat the game is not waiting on)', base,
    [{ by: 'system', action: { type: 'skipSeat', seat: 1, reason: 'host' } }, 'skip_not_allowed']);

  return { description: 'V15 (g): every engine rejection path (all EngineReasonCodes but internal_error), in D18a precedence.', cases };
}

// ── U5: friendly robber with its fallback (design §5.3, R9) ─────────────────────────────────────────────────

/**
 * Settlements for seats 1–3 (at most `perSeat` each) such that every non-desert hex has a corner settlement: greedy by
 * newly covered hexes, under the distance rule, avoiding `avoid`.
 */
function coverAllHexes(perSeat: number, avoid: readonly VertexId[]): VertexId[][] {
  const desert: HexId = 'h:0,0';
  const uncovered = new Set(T.hexes.filter((h) => h !== desert));
  const taken: VertexId[] = [...avoid];
  const bySeat: VertexId[][] = [[], [], []];
  for (let k = 0; uncovered.size > 0; k++) {
    const seat = k % 3;
    if (bySeat[seat]!.length >= perSeat) throw new Error('U5: cannot cover every hex');
    const free = T.vertices.filter((v) => !taken.includes(v) && T.vertexNeighbours(v).every((n) => !taken.includes(n)));
    const best = free.reduce((a, b) => (gain(b) > gain(a) ? b : a));
    function gain(v: VertexId): number {
      return T.vertexHexes(v).filter((h) => uncovered.has(h)).length;
    }
    if (gain(best) === 0) throw new Error('U5: no vertex covers a new hex');
    bySeat[seat]!.push(best);
    taken.push(best);
    for (const h of T.vertexHexes(best)) uncovered.delete(h);
  }
  return bySeat;
}

function friendlyRobberFixture() {
  const home: VertexId = 'v:0,0,N';
  const [s1, s2, s3] = coverAllHexes(4, [home]) as [VertexId[], VertexId[], VertexId[]];
  // The threshold is the largest seat's VP, so every seat 1–3 is shielded.
  const rules = { friendlyRobber: { enabled: true, maxPublicVp: Math.max(s1.length, s2.length, s3.length) } };
  const hands = { 1: { ore: 1 }, 2: { wool: 1 }, 3: { grain: 1 } } as const;
  const shielded = {
    rules,
    pieces: [
      { seat: 0, settlements: [home] },
      { seat: 1, settlements: s1 },
      { seat: 2, settlements: s2 },
      { seat: 3, settlements: s3 },
    ],
    hands,
    turn: { number: 5 },
    phase: { name: 'moveRobber', resume: 'main' },
  } satisfies StateSpec;
  // Every hex but the robber's touches a shielded seat (public VP ≤ maxPublicVp), so the restriction lifts (R9).
  const fallback = recordCase('fallback: every hex is shielded, so every hex but the robber\'s is legal', shielded, (s, i) => {
    if (i > 0) return null;
    const targets = legalActions(s, 0).moveRobber;
    if (targets.length !== T.hexes.length - 1) throw new Error(`U5 fallback: expected ${T.hexes.length - 1} targets, got ${targets.length}`);
    const t = targets.find((x) => x.victims.includes(1))!;
    return [cmd(0, { type: 'moveRobber', hex: t.hex, victim: 1 })];
  });
  // Seat 3 above the threshold (every site a city, 2 VP each): the hexes only it touches open up; a hex still
  // touching seats 1/2 is refused.
  const partial = {
    ...shielded,
    pieces: [
      { seat: 0, settlements: [home] },
      { seat: 1, settlements: s1 },
      { seat: 2, settlements: s2 },
      { seat: 3, cities: s3 },
    ],
  } satisfies StateSpec;
  const restricted = recordCase('restriction holds: only hexes touching no shielded seat are legal; a shielded hex is refused', partial, (s, i) => {
    if (i > 1) return null;
    const targets = legalActions(s, 0).moveRobber;
    if (targets.length === 0 || targets.length === T.hexes.length - 1) throw new Error(`U5 partial: ${targets.length} targets`);
    const shieldedHex = T.hexes.find((h) => h !== s.robber && !targets.some((t) => t.hex === h))!;
    if (i === 0) return [cmd(0, { type: 'moveRobber', hex: shieldedHex, victim: null }), 'invalid_robber_hex'];
    return [cmd(0, { type: 'moveRobber', hex: targets[0]!.hex, victim: targets[0]!.victims[0] ?? null })];
  });
  return {
    description: 'U5: the friendly robber restriction and its fallback when no hex is left (design §5.3, R9).',
    cases: [fallback, restricted],
  };
}

/** Writes a fixture, dropping each case's in-memory end state. */
const write = (name: string, fixture: { description: string; cases: ReturnType<typeof recordCase>[] }) => {
  const cases = fixture.cases.map((c) => ({ name: c.name, buildStateSpec: c.buildStateSpec, initialStateHash: c.initialStateHash, steps: c.steps }));
  writeFileSync(new URL(name, OUT), `${JSON.stringify({ ...fixture, cases }, null, 2)}\n`);
};

write('eint-c-dev-cards.json', devCardsFixture());
write('eint-d-awards.json', awardsFixture());
write('eint-f-seven.json', sevenFixture());
write('eint-g-rejections.json', rejectionsFixture());
write('eint-u5-friendly-robber.json', friendlyRobberFixture());
